config/routes.rb
Rails.application.routes.draw do
  resources :listing_destinations

  resources :features, only: [:index] do
    collection do
      get 'contents'
      resources :kyoto, :controller => 'features', only: [] do
        get '/' => 'features#kyoto', on: :collection
        get '/' => 'features#contents_kyoto', on: :member
      end
      resources :beppu, :controller => 'features', only: [] do
        get '/' => 'features#beppu', on: :collection
        get '/' => 'features#contents_beppu', on: :member
      end
    end
  end

  resources :ga_campaign_tags, param: :short_url, path: 'cp', only: [:show]

  mount Ckeditor::Engine => '/ckeditor'

  get 'static_pages/cancel_policy_en'
  get 'static_pages/service_agreement_en'
  get 'static_pages/specific_commercial_transactions_en'
  get 'static_pages/privacy_policy_en'
  get 'static_pages/cancel_policy_jp'
  get 'static_pages/service_agreement_jp'
  get 'static_pages/specific_commercial_transactions_jp'
  get 'static_pages/privacy_policy_jp'
  get 'static_pages/about'
  get 'static_pages/plan4U'
  get 'static_pages/plan4U_kyoto', :path => 'static_pages/plan4U-kyoto'
  get 'static_pages/plan4U_hokkaido', :path => 'static_pages/plan4U-hokkaido'
  get 'static_pages/plan4U_kyushu', :path => 'static_pages/plan4U-kyushu'
  get 'static_pages/three_reasons'
  get 'static_pages/our_partners'

  post 'currencies/change_currency'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin::Devise.config
  # begin
  #   ActiveAdmin.routes(self)
  # rescue Exception => e
  #   puts "ActiveAdmin: #{e.class}: #{e}"
  # end

  resources :announcements, param: :page_url, only: [:show, :index]
  resources :reports, only: [:create]
  resources :tag_events, only: [:create]

  resources :profiles do
    resources :profile_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      put 'change_order', on: :collection
      post 'create_cover_image', on: :collection
      post 'check_validation', on: :collection
    end
    resources :profile_videos, only: [:destroy] do
      patch 'upload_video', on: :collection
    end
    resources :profile_banks
    resources :profile_identities, only: [:new, :edit, :create, :update, :destroy]

    member do
      get 'self_introduction',    action: 'self_introduction'
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      delete 'delete_category',    action: 'delete_category'
    end
  end
  
  resources :withdrawals, only: [:index] do
   post 'apply', on: :collection
  end

  get 'dashboard'                           => 'dashboard#index'
  get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
  get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
  get 'dashboard/favorite_histories' => 'dashboard#favorite_histories'
  get 'dashboard/read_more_favorites' => 'dashboard#read_more_favorites'
  post 'dashboard/get_chart_data' => 'dashboard#get_chart_data'
  # get 'reviews'                             => 'profiles#review', as: 'user_review'
  # get 'introductions'                       => 'profiles#introduction', as: 'introduction'
  #get 'pickups/show/:type/:id'                    => 'listing_pickups#show', as: 'pickups_list'

  resources :message_threads, except: [:edit] do
    get 'talk_to_me', on: :member
    post 'what_talk_about', on: :member
    patch 'start_planning', on: :member
    get 'change_language', on: :collection
    post 'create_tomo_dachi_messages', on: :member
  end

  resources :messages do
    collection do
      get 'show_preview'
      get 'download_attached_file'
    end
  end

  resources :pre_mails, only: [:create]

  namespace :search do
    get '/', action: :search
    get 'get_information', action: 'get_information'
    get 'search_result', action: 'search_result'
    #get 'page/:page',    action: 'index'
  end

  resources :listings do
    resources :unscheduled_tours, only: [:new, :create, :show], param: :uuid do
      member do
        get 'complete'
      end
      resource :reviews, only: [:create] do
        get '/', action: :unscheduled_tour
        post '/', action: :create_unscheduled_tour
      end
    end
    
    resources :listing_users, only: [:index, :create, :destroy] do
      # member do
      #   post 'accept'
      #   patch 'add_receptionist'
      # end
    end
    
    resources :listing_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      post 'upload_video_cover_image', on: :collection
      put 'change_order', on: :collection
      delete 'destroy_video', on: :collection
      post 'set_category', on: :member
    end
    resources :listing_details, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
    end

    get 'publish',   action: 'publish',   as: 'publish'
    get 'unpublish', action: 'unpublish', as: 'unpublish'
    get 'preview'
    post 'copy', action: 'copy', as: 'copy'
    post 'change_authorized_user_status'
    member do
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      get 'search'
    end

    resources :ngevents, only: [:create] do
      get 'listing_ngdays', on: :collection
      get 'listing_reservation_ngdays', on: :collection
      get 'listing_request_ngdays', on: :collection
      get 'reservation_except_listing_ngdays', on: :collection
      get 'request_except_listing_ngdays', on: :collection
    end
    resources :ngevent_weeks, only: [:create] do
      get 'listing_ngweeks', on: :collection
      put 'unset', on: :collection
    end
    #resources :calendar
  end

  #resources :spots

  resources :favorites, only: [:create, :destroy] do
    collection do
      get :users
      get :listings
      #get :spots
    end
  end

  resources :pickups, only: [:show]
  resources :friends, only: [:index, :destroy] do
    member do
      post 'send_request'
      post 'accept'
      post 'reject'
    end
    collection do
      get 'list_search'
      get 'search'
      get 'search_friends'
      post 'set_selected_guides'
    end
  end

  resources :reservations, only: [:create, :update] do
    resource :reviews, only: [:create] do
      collection do
        get 'for_guest'
        get 'for_guide'
        post 'create_guest'
        post 'create_guide'
      end
    end
    collection do
      get 'confirm_payment'
      get 'cancel_payment'
      get 'set_reservation_by_listing'
      get 'set_reservation_default'
      get 'set_ngday_reservation_by_listing'
      get 'set_ngday_reservation_default'
      get 'exist_ngday_reservation'
    end
    member do
      get 'friends_list' => 'friends#friends_list'
      post 'send_message_to_selected_guides' => 'friends#send_message_to_selected_guides'
    end
  end

  resources :wishlists
  resources :ngevents do
    get 'reservation_ngdays', on: :collection
    get 'request_ngdays', on: :collection
    get 'common_ngdays', on: :collection
    get 'set_ngday_listing', on: :collection
    get 'select_ngdays', on: :collection
  end
  resources :ngevent_weeks do
    get 'except_common_ngweeks', on: :collection
    get 'common_ngweeks', on: :collection
    get 'set_ngweek_listing', on: :collection
    put 'unset', on: :collection
  end
  resources :calendar do
    get 'common_ngdays', on: :collection
  end

  scope "(:locale)", locale: /ja|en/ do
    resources :help_topics do
      get 'for_user',  on: :collection
      get 'for_guide', on: :collection
      get 'search', on: :collection, action: 'search'
      get 'search_result', on: :collection, action: 'search_result'
    end
  end

  devise_for :users, controllers: {
    sessions:            'users/sessions',
    registrations:       'users/registrations',
    passwords:           'users/passwords',
    omniauth_callbacks:  'users/omniauth_callbacks',
    confirmations:       'users/confirmations'
  }

  devise_scope :user do
    get 'users/withdraw' => 'users/registrations#withdraw'
    get 'users/clear_auth_session' => 'users/registrations#clear_auth_session'
    post 'users/create_email' => 'users/registrations#create_email'
    post 'users/before_omniauth' => 'users/registrations#before_omniauth'
  end

  get "weekly_payment_report" => 'admin/payment#payment_weekly_report'
  get "payment_report_index" => 'admin/payment#index'
  root 'welcome#index'
  
  namespace :api, format: 'json' do
    namespace :v1 do
      post 'users/sign_in_via_email'     => 'users#sign_in_via_email'
      get 'listings'     => 'listings#index'
      post 'count_up'     => 'counts#add'
    end
  end
  
  resources :counts, only: [:index, :show]

  #get '*path', controller: 'application', action: 'render_404'
end

app/models/spot.rb
# == Schema Information
#
# Table name: spots
#
#  id                :integer          not null, primary key
#  user_id           :integer          not null
#  title             :string           not null
#  one_word          :string           default("")
#  pickup_id         :integer
#  location          :string           default("")
#  longitude         :decimal(9, 6)
#  latitude          :decimal(9, 6)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  soft_destroyed_at :datetime
#  admin_closed_at   :datetime
#
# Indexes
#
#  index_spots_on_pickup_id  (pickup_id)
#  index_spots_on_user_id    (user_id)
#

class Spot < ActiveRecord::Base
  include Search
  soft_deletable dependent_associations: [:user]
  
  belongs_to :user
  belongs_to :pickup
  has_many :favorites
  has_one :spot_image
  has_many :spot_areas, dependent: :destroy
  has_many :pickups, :through =>  :spot_areas
  
  validates :title, presence: true
  validates :one_word, presence: true
  validate :has_spot_image?
  
  scope :order_by_updated_at_desc, -> { order('spots.updated_at desc') }
  scope :order_by_favorite_count_desc, -> { select("spots.*, count(favorites.id) AS favorites_count").
                                joins("LEFT JOIN favorites ON spots.id = favorites.spot_id and favorites.soft_destroyed_at is null").
                                group("spots.id").
                                order("favorites_count DESC, spots.updated_at DESC")}
  scope :mine, -> user_id { where(user_id: user_id) }
  scope :opened, -> { where(admin_closed_at: nil).joins(:user).merge(User.open) }
  
  accepts_nested_attributes_for :spot_image
  
  def has_spot_image?
    errors.add(:base, Settings.spot_image.save.blank) if self.spot_image.blank?
  end
  
  def near_spots
    list = []
    if self.longitude.present? && self.latitude.present?
      Spot.without_soft_destroyed.opened.where.not(id: self.id).order_by_updated_at_desc.each do |spot|
        if spot.longitude.present? && spot.latitude.present?
          distance = Search.distance(self.longitude, self.latitude, spot.longitude, spot.latitude)
          if distance < Settings.search.distance
            list.push(spot)
          end
        end
      end
      return list.sample(3)
    else
      return nil
    end
  end
  
  def self.search(search_params, max_distance=Settings.search.distance)
    if search_params["longitude"].present? && search_params["latitude"].present?
      if search_params["spot_category"].present?
        spots = Spot.without_soft_destroyed.opened.where.not(latitude: nil, longitude: nil).where(pickup_id: search_params["spot_category"])
      else
        spots = Spot.without_soft_destroyed.opened.where.not(latitude: nil, longitude: nil)
      end
      spot_id_array = []
      spots.each do |spot|
        distance = Search.distance(search_params["longitude"].to_f, search_params["latitude"].to_f, spot.longitude, spot.latitude)
        
        if distance <= max_distance
          spot_id_array.push(spot.id)
        end
      end
      spots = Spot.where(id: spot_id_array)
    end
  end
  
  def self.sort_for_search
    active_spot_ids = self.joins(:user).merge(User.active_users).order_by_favorite_count_desc.map(&:id)
    not_active_spot_ids = self.where.not(id: active_spot_ids).order_by_favorite_count_desc.map(&:id)
    ids = active_spot_ids.concat(not_active_spot_ids).uniq
    spots = self.where(id: ids).order_by_ids(ids)
  end
  
  def self.order_by_ids(ids)
    order_by = ["case"]
    ids.each_with_index.map do |id, index|
      order_by << "WHEN id='#{id}' THEN #{index}"
    end
    order_by << "end"
    order(order_by.join(" "))
  end
  
  def closed?
    return true if self.admin_closed_at.present? or self.user.admin_closed_at.present?
    false
  end
end

app/controllers/api/v1/listings_controller.rb
module Api
  module V1
    class ListingsController < Api::V1::BaseApiController
      before_action :valid_access?
      def index
        user = User.find_by_uuid(params[:user_uuid])
        @listings = Listing.mine(user.id).without_soft_destroyed.order_by_updated_at_desc
        render json: @listings.to_json(include: [:listing_detail, :listing_images]), status: 200
      end
    end
  end
end

app/views/listings/_banner_space.html.slim
/= link_to announcement_path(announcement.page_url) do
  = image_tag(announcement.banner_image_pc, class: 'hide--sp')
  = image_tag(announcement.banner_image_sp, class: 'show--sp')
  = announcement.title

#announcement-banner.row-space-2
  = link_to announcement_path(announcement.page_url), class: "news-banner" do
    .bg-pc.hide--sp[style="background-image: url(#{asset_path announcement.banner_image_pc});"]
    .bg-sp.show--sp[style="background-image: url(#{asset_path announcement.banner_image_sp});"]
    .content.va-container.va-container-wh
      .va-middle.h4.text-contrast.text-center
        b = announcement.title.html_safe

app/views/listings/_edit_link.html.slim
.alert.alert-absolute
  div
    | This is your tour page.
    = link_to edit_listing_path do
      |  Edit this page
      '
      i.fa.fa-chevron-right

app/views/listings/_form.html.slim
.row.row-space-2.row-space-top-2
    .col-lg-12.text-left
      .row-space-2.strong.text-red.listing-manager-notice
        i.fa.fa-exclamation-circle
        | 入力は全て英語で行ってください
= simple_nested_form_for(@listing, html: {class: "form--sp"}) do |f|
  = f.error_notification
  = f.hidden_field :user_id, value: current_user.id
  /= f.hidden_field :open, value: false
  - if current_user.listings.blank?
    = render partial: 'shared/modals/about_guide_tg'
  -if false
    = f.input_field :longitude, as: :string, placeholder: "経度"
    = f.input_field :latitude, as: :string, placeholder: "緯度"
  #tour-title.row.row-space-top-5
    .col-lg-12.text-left
      .h4.row-space-2.text-light
        |  アクティビティのタイトル
  .row
    .col-lg-8
      .required-container
        = f.input_field :title, :class => 'imeoff', placeholder: "Eg. Kamakura vegetable", maxlength: 20
        i.fa.fa-asterisk.balloon[title="required"]
    .col-lg-4.text-left.row-space-top-1
      span 残り
      b#title_counter
      span 文字
  .row.row-space-top-2
    .col-lg-8
      = f.input_field :title_2, :class => 'imeoff', placeholder: "Eg. food-fest for girls! ", maxlength: 20
    .col-lg-4.text-left.row-space-top-1
      span 残り
      b#title_2_counter
      span 文字
  hr
  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left.listing-manager-intaview
      .h4.row-space-2.border-block.text-light
        | アクティビティのこだわりインタビュー
  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h5.row-space-2.text-light
        | このアクティビティの一番の見どころは何ですか？
    .col-12
      .required-container
        = f.input_field :interview2,:class => 'imeoff'
        i.fa.fa-asterisk.balloon[title="required"]
  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h5.row-space-2.text-light
        | このアクティビティを作ったきっかけは何ですか？
    .col-12
      .required-container
        = f.input_field :interview1,:class => 'imeoff'
        i.fa.fa-asterisk.balloon[title="required"]
  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h5.row-space-2.text-light
        | どんな人にオススメですか？
    .col-12
      .required-container
        = f.input_field :interview3,:class => 'imeoff'
        i.fa.fa-asterisk.balloon[title="required"]
  hr
  #tour-overview.row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h4.row-space-2.text-light
        |  アクティビティの概要
    .col-lg-12
      .required-container
        = f.input_field :overview, :class => 'imeoff', placeholder: "このアクティビティのテーマと流れを簡単に入力ください", rows: "12"
        i.fa.fa-asterisk.balloon[title="required"]
  hr    
  = f.simple_fields_for :listing_detail do |ff|
    .row.row-space-2.row-space-top-5
      .col-lg-12.text-left.listing-manager-intaview
        .h4.row-space-2.border-block.text-light
          | アクティビティの条件
    .row.row-space-5.row-space-top-2
      .col-lg-5.text-left.row-space-2
        .h4.text-light.required-container
          | アクティビティの所要時間（目安）
          i.fa.fa-asterisk.balloon[title="required"]
      .col-lg-7.fieldset
        .row
          .col-xs-11
            .select.select-opt.opt-double
              /= f.select :time_required, [*(0..48)].map{|i| (i * 0.5)}, {}, {class: "value_fragile"}
              = ff.select :time_required, set_time_required , {}, {class: "value_fragile"}
              span 時間
    .row.row-space-8.row-space-top-5
      .col-lg-5.text-left.row-space-2
        .h4.text-light.required-container
          | アクティビティの参加者
          i.fa.fa-asterisk.balloon[title="required"]
      .col-lg-7.fieldset
        .row
          .col-xs-11
            .select.select-opt
              = ff.select :min_num_of_people, [*(1..20)], {}, {class: ""}
              span 人から
            .select.select-opt.select_max_num_of_people
              = ff.select :max_num_of_people, [*(1..20)], {}, {class: ""}
              span 人まで
  hr
  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h4.text-light
        | このアクティビティの対応言語
      .text-red.row-space-top-1.row-space-1
        | *You can't uncheck. English is required in Huber.
    .col-lg-12.text-left
      .row
        = collection_check_boxes(:listing, :language_ids, Language.ordered, :id, :name, checked: checked_listing_language_ids(@listing), disabled: disabled_language_id) do |l|
          .col-xs-6.col-lg-3
            = l.label(class: "checkbox-inline") { l.check_box + l.text }
  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h4.text-light
        | カテゴリ
      p.row-space-top-1
        | Choose 
        b three categories 
        | that appeal to you the most. 
    .col-lg-12.text-left
      .listing_pickuptag_checkbox
        = collection_check_boxes(:listing, :pickup_ids, PickupTag.all, :id, :short_name) do |b|
          = b.label(class: "col-xs-6 col-lg-3 small2 row-space-2") { b.check_box(style: "background-image: url(#{asset_path b.object.icon})") + b.text}
  .row.row-space-5.row-space-top-5.row-table
    .col-lg-12.text-left
      .h4.row-space-2.text-light
        |  エリア
        button.btn.btn-primary.listing-manager-area[type="button"] 追加する
    .col-lg-12
      .listing-manager-area-container

  #listing_area.modal[role="dialog" aria-hidden="true"]
    .modal-table
      .modal-cell
        .modal-content
          .card-header
            = link_to "", "#", class: "modal-close", data: {dismiss: "modal"}
            | アクティビティのエリアを選択してください
          .card-body
            .row
              = collection_check_boxes(:listing, :pickup_ids, PickupArea.all, :id, :short_name) do |b|
                = b.label(class: "col-lg-4, col-xs-6") { b.check_box + b.text }
          .card-footer
            button.btn.btn-primary.listing-manager-area-submit[type="button"] OK
                
  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h4.row-space-2.text-light
        | 目的地
    .col-lg-12.text-left
      .row.row-condensed
        - @listing.listing_destinations.each do |listing_destination|
          = f.simple_fields_for :listing_destinations, listing_destination do |ff|
            .col-10.row-space-1.row-space-top-1
              = ff.hidden_field :longitude
              = ff.hidden_field :latitude
              = ff.input_field :location, placeholder: "Googleマップから検索できます"
            .col-2.row-space-1.row-space-top-1
              = ff.link_to_remove do
                span.location-remove.balloon[title="この目的地を削除"]
                  i.fa.fa-times.fa-red.fa-size-1
        = f.link_to_add :listing_destinations, class: "" do
          .col-lg-12
            i.fa.fa-plus
            ' 
            | 新しい目的地を追加する
  #map-wrapper.row.row-space-5.row-space-top-5
    .col-lg-12
      #map
      
  = f.simple_fields_for :listing_detail do |ff|
    .row.row-space-5.row-space-top-5
      .col-lg-12.text-left
        .h4.row-space-2.text-light
          | 集合場所や目印についての説明
      .col-lg-12
        = ff.input_field :place_memo,:class => 'imeoff', placeholder: "Eg. We will meet at the pharmacy next to the South Exit of the station. "

  .row.row-space-5.row-space-top-5
    .col-lg-12.text-left
      .h4.row-space-2.text-light#tour-notes
        | もちもの・注意事項
    .col-lg-12
      = f.input_field :notes, :class => 'imeoff', placeholder: "", rows: "12"

  = f.simple_fields_for :listing_detail do |ff|
    #tour-condition.row.row-space-5.row-space-top-5
      .col-lg-12.text-left
        .h4.row-space-2.text-light
          | 参加条件
      .col-12
        = ff.input_field :condition,:class => 'imeoff', placeholder: "Eg. This tour is only for girls. "
    .row.row-space-5.row-space-top-5
      .col-lg-12.text-left.stop_if_rain
        = ff.input_field :stop_if_rain, inline_label: '雨天の場合は中止する'
  hr
  .row.row-space-top-6
    .col-xs-9.col-offset-3.text-reset-center
      - if 'edit' == controller.action_name
        = f.button :submit, "保存して次のステップへ", class: "btn-primary btn-large", id: 'listing-manager-listing-submit'
      - else
        = f.button :submit, "次へ", class: "btn-primary btn-large"

app/views/listings/_member_request.html.slim
#member_request.modal[role="dialog" aria-hidden="true"]
  .modal-table
    .modal-cell
      .modal-content
        = simple_form_for(ListingUser.new, url: listing_listing_users_path(@listing), method: :post) do |f|
          = f.hidden_field :user_id, value: current_user.id
          = f.hidden_field :listing_id, value: @listing.id
          = f.hidden_field :user_status, value: 'pending'
          .card-header
            strong
              | Write a message
          .card-body
            = f.input_field :request_message, rows: 6, placeholder: "Hi! I'm Kiwako.I would like to join this activity because...Thank you!"
            .card-footer
              = f.submit "Apply to join activity", class: "btn btn-primary"
              = link_to "Close", "#", data: {dismiss:"modal"}, class: "btn"

app/views/listings/_member_request_link.html.slim
.preview_link
  .row.row-space-top-2.row-space-2
    .col-lg-12.text-center
      p.text-lead.text-light.row-space-2
        | このActivityを案内したい場合は以下の「このActivityを案内する」ボタンを押してください。
      = simple_form_for(ListingUser.new, url: listing_listing_users_path(@listing), method: :post) do |f|
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :listing_id, value: @listing.id
        = f.hidden_field :user_status, value: 'member'
        = f.submit "このActivityを案内する", class: "btn btn-primary"
        /= link_to "このActivityを案内する", '#', 'data-toggle' => "modal", 'data-target' => '#member_request', class: "btn btn-primary"
        = link_to "キャンセル", :back, class: "btn btn-default", id: 'cancel_member_request'
/= render partial: "member_request"

app/views/listings/_review_item.html.slim
#listing_reviews
  - reviews.each do |review|
    .row
      - if review.tour_image.present?
        .col-md-12.row-space-4
          .media-cover-img
            = link_to "", "#{asset_path review.tour_image}", class: "review-pic", style: "background-image: url('#{asset_path review.tour_image}')"
            /.review-pic[style="background-image: url('#{asset_path review.tour_image}')"]
            /= image_tag(review.tour_image, class: "review-pic hide")
      = link_to profile_path(user_id_to_profile_id(review.guest_id))
        .col-md-3.text-center.row-space-2
          .media-photo.media-round.media-avatar.text-center
            = link_to profile_path(user_id_to_profile_id(review.guest_id)) do
              .size68[style="background-image: url('#{asset_path user_id_to_profile_image_thumb(review.guest_id)}')"]
          .name
            .text-muted.link-reset.text-truncate
              = link_to profile_path(user_id_to_profile_id(review.guest_id)), class: "text-muted" do
                = user_id_to_firstname(review.guest_id)
      .col-md-9
        .row-space-2
          .expandable
            .expandable-trigger-more
              .expandable-content
                .expandable-inner
                  p
                    = simple_format(h(review.msg))
                  .expandable-indicator
            = link_to "#", class: "expandable-trigger-more expandable-trigger-more-text strong" do
              | read more
    .row.row-space-2
        .col-md-9.col-md-push-3
          .small1.text-right.text-muted
            = review.try('created_at').strftime("%m/%d %H:%M") || ''
          hr.row-space-top-1

  - if reviewed_count > reviews.count
    .row.text-center
      = link_to 'Read more reviews', '#', class: 'btn btn-default read_reviews_link', current_count: reviews.count, reviewed_as: 'guide'

app/views/listings/index.html.slim
/ listings#index
= render 'shared/subnav'
.page-container.row-space-top-8.row-space-4
  .row
    .col-lg-2
      = render partial: "shared/host_sidenav"

    - if @listings.blank? && @listing_users.blank?
      .col-lg-10
        .card
          .card-body
            h3
              | あなたのこだわりのアクティビティを登録しましょう！
            p.text-lead.row-space-4
              | + を押すとはじめてアクティビティを作成する方への案内の後、アクティビティ作成画面が表示されます。
              br
              | アクティビティ登録は途中で保存することもできますので、まずは気軽に登録に進んでみましょう。
            /new activity
            = link_to new_listing_path, class: "btn btn-primary btn-large" do
              | Create Activity
    - else
      .col-lg-10
        .row-space-8.guide_list-wrapper
          .guide_list-tiles
            h2.text-brand.row-space-6
              span My Activities
            .row
              / my activities - open
              - @listings.where(open: true).each do |listing|
                .col-md-6.col-lg-4.row-space-4
                  = render partial: 'shared/listing_card', locals: { profile: current_user.profile, listing: listing}
                  = render partial: 'index_actions', locals: { listing: listing }
              / official activities - open
              - @listing_users_open.each do |listing_user|
                - listing = listing_user.listing
                .col-md-6.col-lg-4.row-space-4
                  = render partial: 'shared/listing_card', locals: { profile: listing_to_profile(listing), listing: listing}
                  = render partial: 'index_actions', locals: { listing: listing }
              / my activities - close
              - @listings.not_opened.each do |listing|
                - if left_step_count_and_elements(listing)[0] == 0
                  .col-md-6.col-lg-4.row-space-4
                    .unpublish-card-container
                      = link_to "", listing_preview_path(listing)
                      = render partial: 'shared/listing_card', locals: { profile: current_user.profile, listing: listing}
                    = render partial: 'index_actions', locals: { listing: listing }
              / official activities - close
              - @listing_users_close.each do |listing_user|
                - listing = listing_user.listing
                .col-md-6.col-lg-4.row-space-4
                  .unpublish-card-container
                    = link_to "", "#"
                    = render partial: 'shared/listing_card', locals: { profile: listing_to_profile(listing), listing: listing}
                  = render partial: 'index_actions', locals: { listing: listing }
              / my activities - edit
              - @listings.not_opened.each do |listing|
                - if left_step_count_and_elements(listing)[0] > 0
                  .col-md-6.col-lg-4.row-space-4
                    .editing-card-container
                      = link_to "", edit_listing_path(listing)
                      = render partial: 'shared/listing_card', locals: { profile: current_user.profile, listing: listing}
                    = render partial: 'index_actions', locals: { listing: listing }
                    
              
              /new activity
              .col-md-6.col-lg-4.row-space-4
                = link_to new_listing_path, class: "add-listing-block" do
                  span.sr-only create activity