config/routes.rb
Rails.application.routes.draw do
  resources :listing_destinations

  resources :features, only: [:index] do
    collection do
      get 'contents'
      resources :kyoto, :controller => 'features', only: [] do
        get '/' => 'features#kyoto', on: :collection
        get '/' => 'features#contents_kyoto', on: :member
      end
      resources :beppu, :controller => 'features', only: [] do
        get '/' => 'features#beppu', on: :collection
        get '/' => 'features#contents_beppu', on: :member
      end
    end
  end

  resources :ga_campaign_tags, param: :short_url, path: 'cp', only: [:show]

  mount Ckeditor::Engine => '/ckeditor'

  get 'static_pages/cancel_policy_en'
  get 'static_pages/service_agreement_en'
  get 'static_pages/specific_commercial_transactions_en'
  get 'static_pages/privacy_policy_en'
  get 'static_pages/cancel_policy_jp'
  get 'static_pages/service_agreement_jp'
  get 'static_pages/specific_commercial_transactions_jp'
  get 'static_pages/privacy_policy_jp'
  get 'static_pages/about'
  get 'static_pages/plan4U'
  get 'static_pages/plan4U_kyoto', :path => 'static_pages/plan4U-kyoto'
  get 'static_pages/plan4U_hokkaido', :path => 'static_pages/plan4U-hokkaido'
  get 'static_pages/plan4U_kyushu', :path => 'static_pages/plan4U-kyushu'
  get 'static_pages/three_reasons'
  get 'static_pages/our_partners'

  post 'currencies/change_currency'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin::Devise.config
  # begin
  #   ActiveAdmin.routes(self)
  # rescue Exception => e
  #   puts "ActiveAdmin: #{e.class}: #{e}"
  # end

  resources :announcements, param: :page_url, only: [:show, :index]
  resources :reports, only: [:create]
  resources :tag_events, only: [:create]

  resources :profiles do
    resources :profile_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      put 'change_order', on: :collection
      post 'create_cover_image', on: :collection
      post 'check_validation', on: :collection
    end
    resources :profile_videos, only: [:destroy] do
      patch 'upload_video', on: :collection
    end
    resources :profile_banks
    resources :profile_identities, only: [:new, :edit, :create, :update, :destroy]

    member do
      get 'self_introduction',    action: 'self_introduction'
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      delete 'delete_category',    action: 'delete_category'
    end
  end
  
  resources :withdrawals, only: [:index] do
   post 'apply', on: :collection
  end

  get 'dashboard'                           => 'dashboard#index'
  get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
  get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
  get 'dashboard/favorite_histories' => 'dashboard#favorite_histories'
  get 'dashboard/read_more_favorites' => 'dashboard#read_more_favorites'
  post 'dashboard/get_chart_data' => 'dashboard#get_chart_data'
  # get 'reviews'                             => 'profiles#review', as: 'user_review'
  # get 'introductions'                       => 'profiles#introduction', as: 'introduction'
  #get 'pickups/show/:type/:id'                    => 'listing_pickups#show', as: 'pickups_list'

  resources :message_threads, except: [:edit] do
    get 'talk_to_me', on: :member
    post 'what_talk_about', on: :member
    patch 'start_planning', on: :member
    get 'change_language', on: :collection
    post 'create_tomo_dachi_messages', on: :member
  end

  resources :messages do
    collection do
      get 'show_preview'
      get 'download_attached_file'
    end
  end

  resources :pre_mails, only: [:create]

  namespace :search do
    get '/', action: :search
    get 'get_information', action: 'get_information'
    get 'search_result', action: 'search_result'
    #get 'page/:page',    action: 'index'
  end

  resources :listings do
    resources :unscheduled_tours, only: [:new, :create, :show], param: :uuid do
      member do
        get 'complete'
      end
      resource :reviews, only: [:create] do
        get '/', action: :unscheduled_tour
        post '/', action: :create_unscheduled_tour
      end
    end
    
    resources :listing_users, only: [:index, :create, :destroy] do
      # member do
      #   post 'accept'
      #   patch 'add_receptionist'
      # end
    end
    
    resources :listing_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      post 'upload_video_cover_image', on: :collection
      put 'change_order', on: :collection
      delete 'destroy_video', on: :collection
      post 'set_category', on: :member
    end
    resources :listing_details, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
    end

    get 'publish',   action: 'publish',   as: 'publish'
    get 'unpublish', action: 'unpublish', as: 'unpublish'
    get 'preview'
    post 'copy', action: 'copy', as: 'copy'
    post 'change_authorized_user_status'
    member do
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      get 'search'
    end

    resources :ngevents, only: [:create] do
      get 'listing_ngdays', on: :collection
      get 'listing_reservation_ngdays', on: :collection
      get 'listing_request_ngdays', on: :collection
      get 'reservation_except_listing_ngdays', on: :collection
      get 'request_except_listing_ngdays', on: :collection
    end
    resources :ngevent_weeks, only: [:create] do
      get 'listing_ngweeks', on: :collection
      put 'unset', on: :collection
    end
    #resources :calendar
  end

  #resources :spots

  resources :favorites, only: [:create, :destroy] do
    collection do
      get :users
      get :listings
      #get :spots
    end
  end

  resources :pickups, only: [:show]
  resources :friends, only: [:index, :destroy] do
    member do
      post 'send_request'
      post 'accept'
      post 'reject'
    end
    collection do
      get 'list_search'
      get 'search'
      get 'search_friends'
      post 'set_selected_guides'
    end
  end

  resources :reservations, only: [:create, :update] do
    resource :reviews, only: [:create] do
      collection do
        get 'for_guest'
        get 'for_guide'
        post 'create_guest'
        post 'create_guide'
      end
    end
    collection do
      get 'confirm_payment'
      get 'cancel_payment'
      get 'set_reservation_by_listing'
      get 'set_reservation_default'
      get 'set_ngday_reservation_by_listing'
      get 'set_ngday_reservation_default'
      get 'exist_ngday_reservation'
    end
    member do
      get 'friends_list' => 'friends#friends_list'
      post 'send_message_to_selected_guides' => 'friends#send_message_to_selected_guides'
    end
  end

  resources :wishlists
  resources :ngevents do
    get 'reservation_ngdays', on: :collection
    get 'request_ngdays', on: :collection
    get 'common_ngdays', on: :collection
    get 'set_ngday_listing', on: :collection
    get 'select_ngdays', on: :collection
  end
  resources :ngevent_weeks do
    get 'except_common_ngweeks', on: :collection
    get 'common_ngweeks', on: :collection
    get 'set_ngweek_listing', on: :collection
    put 'unset', on: :collection
  end
  resources :calendar do
    get 'common_ngdays', on: :collection
  end

  scope "(:locale)", locale: /ja|en/ do
    resources :help_topics do
      get 'for_user',  on: :collection
      get 'for_guide', on: :collection
      get 'search', on: :collection, action: 'search'
      get 'search_result', on: :collection, action: 'search_result'
    end
  end

  devise_for :users, controllers: {
    sessions:            'users/sessions',
    registrations:       'users/registrations',
    passwords:           'users/passwords',
    omniauth_callbacks:  'users/omniauth_callbacks',
    confirmations:       'users/confirmations'
  }

  devise_scope :user do
    get 'users/withdraw' => 'users/registrations#withdraw'
    get 'users/clear_auth_session' => 'users/registrations#clear_auth_session'
    post 'users/create_email' => 'users/registrations#create_email'
    post 'users/before_omniauth' => 'users/registrations#before_omniauth'
  end

  get "weekly_payment_report" => 'admin/payment#payment_weekly_report'
  get "payment_report_index" => 'admin/payment#index'
  root 'welcome#index'
  
  namespace :api, format: 'json' do
    namespace :v1 do
      post 'users/sign_in_via_email'     => 'users#sign_in_via_email'
      get 'listings'     => 'listings#index'
      post 'count_up'     => 'counts#add'
    end
  end
  
  resources :counts, only: [:index, :show]

  #get '*path', controller: 'application', action: 'render_404'
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                   :integer          not null, primary key
#  user_id              :integer          not null
#  first_name           :string           default("")
#  last_name            :string           default("")
#  birthday             :date
#  gender               :integer
#  phone                :string           default("")
#  phone_verification   :boolean          default(FALSE)
#  zipcode              :string           default("")
#  location             :string           default("")
#  self_introduction    :text             default("")
#  school               :string           default("")
#  work                 :string           default("")
#  timezone             :string           default("")
#  listing_count        :integer          default(0)
#  wishlist_count       :integer          default(0)
#  bookmark_count       :integer          default(0)
#  reviewed_count       :integer          default(0)
#  reservation_count    :integer          default(0)
#  ave_total            :float            default(0.0)
#  ave_accuracy         :float            default(0.0)
#  ave_communication    :float            default(0.0)
#  ave_cleanliness      :float            default(0.0)
#  ave_location         :float            default(0.0)
#  ave_check_in         :float            default(0.0)
#  ave_cost_performance :float            default(0.0)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  country              :string           default("")
#  progress             :integer          default(0), not null
#  prefecture           :string           default("")
#  municipality         :string           default("")
#  other_address        :string           default("")
#  soft_destroyed_at    :datetime
#  free_field           :text             default("")
#  planning_for_you     :boolean
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#

class Profile < ActiveRecord::Base
  acts_as_taggable
  soft_deletable
  soft_deletable dependent_associations: [:user]
  
  before_save :setting_countries
  
  belongs_to :user
  has_one :profile_video, dependent: :destroy
  has_one :profile_identity, dependent: :destroy
  has_one :profile_bank, dependent: :destroy
  has_one :profile_keyword, dependent: :destroy
  has_many :profile_images, dependent: :destroy
  has_many :profile_categories, dependent: :destroy
  has_many :categories, :through => :profile_categories, dependent: :destroy
  has_many :profile_languages, dependent: :destroy
  has_many :languages, :through => :profile_languages, dependent: :destroy
  has_many :profile_countries, dependent: :destroy
  has_many :profile_pickups, dependent: :destroy
  has_many :pickups, :through =>  :profile_pickups

  enum gender: { female: 0, male: 1, others: 2, not_specified: 3 }

  attr_accessor :enable_strict_validation
  accepts_nested_attributes_for :profile_categories, allow_destroy: true
  accepts_nested_attributes_for :profile_countries, allow_destroy: true
  accepts_nested_attributes_for :profile_pickups, allow_destroy: true
  accepts_nested_attributes_for :profile_video, allow_destroy: true

  validates :user_id, presence: true, on: :update
  validates :user_id, uniqueness: true
  validate :last_name_presence, if: :enable_strict_validation, on: :update
  validates :first_name, :country, :phone, presence: true, if: :enable_strict_validation, on: :update
  VALID_PHONE_REGEX = /\A[-+0-9]+\z/
  validates :phone, format: { with: VALID_PHONE_REGEX, if: :enable_strict_validation, on: :update }
  validates :first_name, presence: true, if: :first_name_needed
  
  attr_accessor :first_name_needed
  
  scope :contains?, -> name { where('last_name ILIKE ? or first_name ILIKE ?', '%' + name + '%', '%' + name + '%') }
  scope :order_by_created_at_asc, -> { order('created_at asc') }
  
  def last_name_presence
    if self.last_name.empty?
      errors[:base] << "Family Name can't be blank"
    end
  end

  def self.minimun_requirement?(user_id)
    profile = Profile.where(user_id: user_id).first
    if profile.first_name.present? &&
      profile.last_name.present? &&
      profile.birthday.present? &&
      profile.phone.present? &&
      profile.location.present? &&
      profile.self_introduction.present?
      return true
    else
      return false
    end
  end

  def self.mine(user_id)
    Profile.where(user_id: user_id).first
  end

  def self.guides
    #user_ids = Listing.where(open: true).pluck(:user_id).uniq
    user_ids = User.main_guide.open.pluck(:id)
    Profile.where(user_id: user_ids).where(planning_for_you: true)
  end
  
  def self.main_and_support_guides
    user_ids = User.main_guide.open + User.support_guide.open
    users = User.where(id: user_ids)
    Profile.where(user_id: users.ids)
  end

  def self.get_percentage(id)
    user = User.find(id)
    hash_result = {}
    if user
      profile = user.profile
      if profile
        #birthday
        hash_result.store('birthday', 'true') if profile.birthday.blank?
        #country
        hash_result.store('country', 'true') if profile.country.blank?
        #location
        hash_result.store('location', 'true') if profile.location.blank?
        #email
        hash_result.store('email', 'true') if user.email.blank?
        #phone
        hash_result.store('phone', 'true') if profile.phone.blank?
        #self_introduction
        hash_result.store('self_introduction', 'true') if profile.self_introduction.blank?

        # Caliculate Remain Percentage
        if hash_result.present?
          ret = (((100 * hash_result.length).to_f / 6).round) / hash_result.length
          hash_result.store('rate', ret) if ret
        end

      end
    end
    hash_result
  end

  def self.set_percentage(id)
    user = User.find(id)
    if user
      profile = user.profile
      if profile
        array_result = []
        #birthday
        array_result << 'birthday' if profile.birthday.present?
        #country
        array_result << 'country' if profile.country.present?
        #location
        array_result << 'location' if profile.location.present?
        #email
        array_result << 'email' if user.email.present?
        #phone
        array_result << 'phone' if profile.phone.present?
        #self_introduction
        array_result << 'self_introduction' if profile.self_introduction.present?

        # Caliculate Percentage
        ret = ((100 / 6.to_f) * array_result.length).round
        profile.progress = ret.to_i
        profile.update({:listing_count => ret})
      end
    end
  end
  
  def cover
    self.profile_images.where(cover_flg: true).first
  end
  
  def thumb_images
    self.profile_images.where.not(cover_flg: true).where.not(image: '').order('order_num')
  end
  
  def thumb_image
    self.thumb_images.first
  end
  
  def self.set_up_update_params(profile_params)
    profile_params[:location] = profile_params[:municipality] + ' ' + profile_params[:prefecture] if profile_params[:municipality]
    if profile_params[:profile_pickups_attributes].present?
      profile_params[:profile_pickups_attributes].each_with_index do |profile_pickup, i|
        if profile_pickup[1]['tag_list'].blank?
          profile_params[:profile_pickups_attributes][profile_pickup[0]]['tag_list'] = ''
        end
      end
    end
    profile_params
  end
  
  def setting_countries
    self.profile_countries.each do |profile_country|
      self.profile_countries.delete(profile_country) if profile_country.country.blank?
    end
  end
  
  def country_name
    if country.present?
      tmp_country = ISO3166::Country[country]
      tmp_country.translations[I18n.locale.to_s] || tmp_country.name
    else
      ''
    end
  end
  
  def official_account?
    user = User.find_by_id(self.user_id)
    user.present? && user.official_account?
  end
end

app/controllers/search_controller.rb
class SearchController < CommonSearchController
  def search
    basic_search
    gon.pickup_areas = PickupArea.list_for_gon
    if request.xhr?
      return render json: { html: render_to_string(partial: 'search/result_block', locals: { results: @results, conditions: @conditions, new_listings: @new_listings }), locations: gon.locations}
    end
  end
  
  def search_result
  end
  
  def get_information
    if request.xhr?
      if params[:target] == 'listings'
        listing = Listing.find_by_id(params[:id])
        return render partial: 'shared/info_window', locals: { target: listing}
      else
        spot = Spot.find_by_id(params[:id])
        return render partial: 'shared/info_window', locals: { target: spot}
      end
    end
  end
end

app/views/search/_filter.html.slim
.filters
  .card-header.filters-section.show--sp.text-center
    = link_to "", "#", class: "modal-close js-small-filters-close"
    | Search
  
  .intro-filter.filters-section.card-body
    .row.row-condensed
      .col-sm-3.col-md-1.row-space-1--sp.text-right
        i.fa.fa-search.fa-brand.fa-size-1
      .col-sm-9.col-md-10
        input.location#location-search[type="text" placeholder="location" value=@conditions['location'] name="search[location]"]
  #tab-tour.hide
    .location-filter.filters-section.card-body.show--sp
      .form
        input#location-search-filter-sp[type="text" placeholder="location" value=@conditions['location'] name="search[location]"]
        i.fa.fa-search.fa-brand
    .category-filters.filters-section.card-body
      .row
        .col-sm-12.col-md-3.text-left.col-subject
          span Category
        .col-sm-12.col-md-9
          .category-filters-inner
            .row.row-condensed
              .col-sm-4.col-md-6.col-lg-4
                .category-select
                  .category-selected
                    span Choose Category
                  .category-radio
                    label.category-default
                      | Choose Category
                      input[name="search[category1]" type="radio" value=""]
                    - PickupTag.all.order_by_created_at_asc.each do |pickup_tag|
                      - checked = @conditions['category1'].to_i == pickup_tag.id
                      label[style="background-image: url(#{ asset_path pickup_tag.icon })"]
                        span = pickup_tag.short_name
                        input#search_category1[name="search[category1]" type="radio" value="#{ pickup_tag.id }" checked=checked ]

              .col-sm-4.col-md-6.col-lg-4
                .category-select
                  .category-selected
                    span Choose Category
                  .category-radio
                    label.category-default
                      | Choose Category
                      input[name="search[category2]" type="radio" value=""]
                    - PickupTag.all.order_by_created_at_asc.each do |pickup_tag|
                      - checked = @conditions['category2'].to_i == pickup_tag.id
                      label[style="background-image: url(#{ asset_path pickup_tag.icon })"]
                        span = pickup_tag.short_name
                        input#search_category2[name="search[category2]" type="radio" value="#{ pickup_tag.id }" checked=checked ]

              .col-sm-4.col-md-6.col-lg-4
                .category-select.last
                  .category-selected
                    span Choose Category
                  .category-radio
                    label.category-default
                      | Choose Category
                      input[name="search[category3]" type="radio" value=""]
                    - PickupTag.all.order_by_created_at_asc.each do |pickup_tag|
                      - checked = @conditions['category3'].to_i == pickup_tag.id
                      label[style="background-image: url(#{ asset_path pickup_tag.icon })"]
                        span = pickup_tag.short_name
                        input#search_category3[name="search[category3]" type="radio" value="#{ pickup_tag.id }" checked=checked ]
    .duration-filter.filters-section.card-body
      .row
        .col-sm-6.col-md-3.text-left.col-subject
          span Duration
        .col-sm-12.col-md-8
          .row-space-top-4.row-space-2
            input#duration-range[name="search[duration_range]" value=@conditions['duration_range'] ]
    .laguage-filter.filters-section.card-body
      .row
        .col-sm-6.col-md-3.text-left.col-subject
          span Language
        .col-sm-12.col-md-9
          .language-select
            = collection_check_boxes(:search, :language_ids, Language.ordered, :id, :name, checked: @conditions['language_ids']) do |l|
              label
                = l.check_box
                span #{language_id_to_short_name(l.value)}
                

  .filter-buttons.filters-section.card-body.text-right.row-space-6
    .default-buttons.hide--sp
      = link_to "#", class: "btn btn-primary show-sort-filter" do
        span.text-more-filters MORE FILTERS
    .apply-buttons
      = link_to "#", class: "btn cancel-filter" do
        span.text-more-filters CANCEL
      = f.button :submit, "APPLY FILTERS", class: "btn btn-primary"










    /! old version ================================================================================
    /.filters-section.intro-filter.card-body
      .row
        .col-lg-2.col-md-12.text-center-sm.text-center-md.filter-label
          label 価格帯
        .col-lg-9.col-md-12
          = f.input_field :price, id: "price-range"
    /.checkbox-group.hosting_amenities.filters-section.card-body
      .row
        .col-lg-2.col-md-12.filter-label
          label お菓子の記述あり（オプション1）
        .col-lg-9.col-md-11
          .row.row-condensed.filters-columns
            .col-md-4
              label.media.checkbox.text-truncate title="オプション1"
                = f.input_field :confection, as: :boolean, boolean_style: :inline, class: "pull-left"
                | お菓子（オプション1）の情報があるものだけ表示
    /.checkbox-group.hosting_amenities.filters-section.card-body
      .row
        .col-lg-2.col-md-12.filter-label
          label お道具（オプション2）
        .col-lg-9.col-md-11
          .row.row-condensed.filters-columns
            .col-md-4
              label.media.checkbox.text-truncate title="オプション2"
                = f.input_field :tool, as: :boolean, boolean_style: :inline, class: "pull-left"
                | お道具（オプション2）の情報があるものだけ表示
    /.checkbox-group.property_type_id.filters-section.card-body
      .row
        .col-lg-2.col-md-12.filter-label
          label 服装（オプション3）
        .col-lg-9.col-md-11
          .row.row-condensed.filters-columns
            .col-md-4
              label.media.checkbox.text-truncate title="オプション3"
                = f.input_field :wafuku, as: :boolean, boolean_style: :inline, class: "pull-left"
                | 和服のみ（オプション3）
    /.keywords.filters-section.card-body
      .row
        .col-lg-2.col-md-12.filter-label
          label その他
        .col-lg-9
          .row.row-condensed
            .col-md-12
              = f.input_field :keywords, placeholder: "キーワード情報", class: "input-block"
    /.filters-footer.card-btn--sp
      = f.button :submit, "ガイドページを表示", class: "btn btn-block btn-large btn-primary search-button row-space-4--sp"
  /.filters-placeholder.hide.hide--sp


  /.sidebar-header.card-body.card-bg-medium.hide--sp.clearfix
    = link_to "#", class: "btn show-filters pull-left" do
      span.text-more-filters 検索条件を追加
    = f.button :submit, "再検索する", class: "btn btn-primary pull-left"

    /.results-count-item.pull-right.text-right
      h1.results-count.h5
        = hit_count
        |件
        |·
        = conditions['location']

app/views/search/_form.html.slim
= simple_form_for(:search, url: path, html: {class: "trip-form", method: 'get', id: 'search_form'}) do |f|
  = f.hidden_field :latitude, value: @conditions['latitude']
  = f.hidden_field :longitude, value: @conditions['longitude']
  = f.hidden_field :sort_by, value: @conditions['sort_by']
  = f.hidden_field :official, value: @conditions['official']
  = f.hidden_field :bounds, value: ''
  .map-search-container
    .sidebar
      .search-trigger--sp.show--sp.page-container
        .row.row-condensed
          .col-sm-8
            input#location-search-sp[type="text" placeholder="location" value=@conditions['location'] name="search[location]"]
            i.fa.fa-search.fa-brand
          .col-sm-4
            = link_to "FILTERS", "#", class: "js-small-filter-show btn btn-block btn-primary"
        - if controller_name == 'listings'
          .row
            .col-sm-12
              = link_to listings_path, aria: {selected: "false"}, class: "sidenav-item" do
                small
                  i.fa.fa-angle-left
                  span<
                  | My Activities

      = render partial: 'search/filter', locals: { hit_count: @hit_count, conditions: @conditions, f: f }
      .sidebar-header-placeholder.show--sp
      = render partial: 'search/result_block', locals: { results: @results, conditions: @conditions, new_listings: @new_listings }
    .map.hide--sp
      - if @results.blank?
        .no-listings-map
          div
            i.fa.fa-map-marker
            p
              | There aren't any results matching your search terms.
      - else
        #map.map-canvas
        .map-refresh-controls.Google
          a.map-manual-refresh.btn.btn-primary.hide
            | 再検索
            i.fa.fa-refresh.fa-space-left
          /.card.map-auto-refresh.hide
            label.checkbox
              input.map-auto-refresh-checkbox checked="checked" type="checkbox"
              small マップを動かして自動検索
= render partial: 'shared/modals/listing_image_loading'
.fixed-btn-container.show--sp
  = link_to "Map", "#", class: 'btn btn-small btn-block btn-primary', id: 'map-or-list-bun'

app/views/search/_result_block.html.slim
#result_block
  - if results.blank?
    .no-listings-block
      div
        p
        | There aren't any results matching your search terms. Please change your search terms and try again.
  - else
    .search-results.touch
      .outer-listings-container.row-space-5.row-space-2-sm
        .row.listings-container
          = render partial: 'search/result_item', locals: { results: results, new_listings: new_listings }
      - if results.num_pages > 1
        .results-footer.text-center
          = paginate results
        /ul.list-inline
          li.active
            = link_to "1", "#"
          li
            = link_to "2", "#"
          li
            = link_to "3", "#"
        

app/views/search/_result_item.html.slim
- if results.present?
  - results.each do |result|
    .col-sm-12.col-md-6.row-space-4
      - if result.is_a?(String)
      - elsif result.model_name == 'Listing'
        = render partial: 'shared/listing_card', locals: { profile: listing_to_profile(result), listing: result}
      /- elsif result.model_name == 'Spot'
        = render partial: 'shared/spot_card', locals: { profile: user_id_to_profile(result.user_id), spot: result}
      
/* New Tours
- if new_listings.present?
  .col-sm-12.row-space-4
    .new-result-block.text-center
      span.h4.text-contrast New Tours
  - new_listings.each do |listing|
    .col-sm-12.col-md-6.row-space-4
      = render partial: 'shared/listing_card', locals: { profile: listing_to_profile(listing), listing: listing}

app/views/search/search.html.slim
= render partial: 'form', locals: { path: search_path }
- unless user_signed_in?
  = render partial: 'shared/modals/sign_up_form'