config/routes.rb
Rails.application.routes.draw do
  resources :listing_destinations

  resources :features, only: [:index] do
    collection do
      get 'contents'
      resources :kyoto, :controller => 'features', only: [] do
        get '/' => 'features#kyoto', on: :collection
        get '/' => 'features#contents_kyoto', on: :member
      end
      resources :beppu, :controller => 'features', only: [] do
        get '/' => 'features#beppu', on: :collection
        get '/' => 'features#contents_beppu', on: :member
      end
    end
  end

  resources :ga_campaign_tags, param: :short_url, path: 'cp', only: [:show]

  mount Ckeditor::Engine => '/ckeditor'

  get 'static_pages/cancel_policy_en'
  get 'static_pages/service_agreement_en'
  get 'static_pages/specific_commercial_transactions_en'
  get 'static_pages/privacy_policy_en'
  get 'static_pages/cancel_policy_jp'
  get 'static_pages/service_agreement_jp'
  get 'static_pages/specific_commercial_transactions_jp'
  get 'static_pages/privacy_policy_jp'
  get 'static_pages/about'
  get 'static_pages/plan4U'
  get 'static_pages/plan4U_kyoto', :path => 'static_pages/plan4U-kyoto'
  get 'static_pages/plan4U_hokkaido', :path => 'static_pages/plan4U-hokkaido'
  get 'static_pages/plan4U_kyushu', :path => 'static_pages/plan4U-kyushu'
  get 'static_pages/three_reasons'
  get 'static_pages/our_partners'

  post 'currencies/change_currency'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin::Devise.config
  # begin
  #   ActiveAdmin.routes(self)
  # rescue Exception => e
  #   puts "ActiveAdmin: #{e.class}: #{e}"
  # end

  resources :announcements, param: :page_url, only: [:show, :index]
  resources :reports, only: [:create]
  resources :tag_events, only: [:create]

  resources :profiles do
    resources :profile_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      put 'change_order', on: :collection
      post 'create_cover_image', on: :collection
      post 'check_validation', on: :collection
    end
    resources :profile_videos, only: [:destroy] do
      patch 'upload_video', on: :collection
    end
    resources :profile_banks
    resources :profile_identities, only: [:new, :edit, :create, :update, :destroy]

    member do
      get 'self_introduction',    action: 'self_introduction'
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      delete 'delete_category',    action: 'delete_category'
    end
  end
  
  resources :withdrawals, only: [:index] do
   post 'apply', on: :collection
  end

  get 'dashboard'                           => 'dashboard#index'
  get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
  get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
  get 'dashboard/favorite_histories' => 'dashboard#favorite_histories'
  get 'dashboard/read_more_favorites' => 'dashboard#read_more_favorites'
  post 'dashboard/get_chart_data' => 'dashboard#get_chart_data'
  # get 'reviews'                             => 'profiles#review', as: 'user_review'
  # get 'introductions'                       => 'profiles#introduction', as: 'introduction'
  #get 'pickups/show/:type/:id'                    => 'listing_pickups#show', as: 'pickups_list'

  resources :message_threads, except: [:edit] do
    get 'talk_to_me', on: :member
    post 'what_talk_about', on: :member
    patch 'start_planning', on: :member
    get 'change_language', on: :collection
    post 'create_tomo_dachi_messages', on: :member
  end

  resources :messages do
    collection do
      get 'show_preview'
      get 'download_attached_file'
    end
  end

  resources :pre_mails, only: [:create]

  namespace :search do
    get '/', action: :search
    get 'get_information', action: 'get_information'
    get 'search_result', action: 'search_result'
    #get 'page/:page',    action: 'index'
  end

  resources :listings do
    resources :unscheduled_tours, only: [:new, :create, :show], param: :uuid do
      member do
        get 'complete'
      end
      resource :reviews, only: [:create] do
        get '/', action: :unscheduled_tour
        post '/', action: :create_unscheduled_tour
      end
    end
    
    resources :listing_users, only: [:index, :create, :destroy] do
      # member do
      #   post 'accept'
      #   patch 'add_receptionist'
      # end
    end
    
    resources :listing_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      post 'upload_video_cover_image', on: :collection
      put 'change_order', on: :collection
      delete 'destroy_video', on: :collection
      post 'set_category', on: :member
    end
    resources :listing_details, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
    end

    get 'publish',   action: 'publish',   as: 'publish'
    get 'unpublish', action: 'unpublish', as: 'unpublish'
    get 'preview'
    post 'copy', action: 'copy', as: 'copy'
    post 'change_authorized_user_status'
    member do
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      get 'search'
    end

    resources :ngevents, only: [:create] do
      get 'listing_ngdays', on: :collection
      get 'listing_reservation_ngdays', on: :collection
      get 'listing_request_ngdays', on: :collection
      get 'reservation_except_listing_ngdays', on: :collection
      get 'request_except_listing_ngdays', on: :collection
    end
    resources :ngevent_weeks, only: [:create] do
      get 'listing_ngweeks', on: :collection
      put 'unset', on: :collection
    end
    #resources :calendar
  end

  #resources :spots

  resources :favorites, only: [:create, :destroy] do
    collection do
      get :users
      get :listings
      #get :spots
    end
  end

  resources :pickups, only: [:show]
  resources :friends, only: [:index, :destroy] do
    member do
      post 'send_request'
      post 'accept'
      post 'reject'
    end
    collection do
      get 'list_search'
      get 'search'
      get 'search_friends'
      post 'set_selected_guides'
    end
  end

  resources :reservations, only: [:create, :update] do
    resource :reviews, only: [:create] do
      collection do
        get 'for_guest'
        get 'for_guide'
        post 'create_guest'
        post 'create_guide'
      end
    end
    collection do
      get 'confirm_payment'
      get 'cancel_payment'
      get 'set_reservation_by_listing'
      get 'set_reservation_default'
      get 'set_ngday_reservation_by_listing'
      get 'set_ngday_reservation_default'
      get 'exist_ngday_reservation'
    end
    member do
      get 'friends_list' => 'friends#friends_list'
      post 'send_message_to_selected_guides' => 'friends#send_message_to_selected_guides'
    end
  end

  resources :wishlists
  resources :ngevents do
    get 'reservation_ngdays', on: :collection
    get 'request_ngdays', on: :collection
    get 'common_ngdays', on: :collection
    get 'set_ngday_listing', on: :collection
    get 'select_ngdays', on: :collection
  end
  resources :ngevent_weeks do
    get 'except_common_ngweeks', on: :collection
    get 'common_ngweeks', on: :collection
    get 'set_ngweek_listing', on: :collection
    put 'unset', on: :collection
  end
  resources :calendar do
    get 'common_ngdays', on: :collection
  end

  scope "(:locale)", locale: /ja|en/ do
    resources :help_topics do
      get 'for_user',  on: :collection
      get 'for_guide', on: :collection
      get 'search', on: :collection, action: 'search'
      get 'search_result', on: :collection, action: 'search_result'
    end
  end

  devise_for :users, controllers: {
    sessions:            'users/sessions',
    registrations:       'users/registrations',
    passwords:           'users/passwords',
    omniauth_callbacks:  'users/omniauth_callbacks',
    confirmations:       'users/confirmations'
  }

  devise_scope :user do
    get 'users/withdraw' => 'users/registrations#withdraw'
    get 'users/clear_auth_session' => 'users/registrations#clear_auth_session'
    post 'users/create_email' => 'users/registrations#create_email'
    post 'users/before_omniauth' => 'users/registrations#before_omniauth'
  end

  get "weekly_payment_report" => 'admin/payment#payment_weekly_report'
  get "payment_report_index" => 'admin/payment#index'
  root 'welcome#index'
  
  namespace :api, format: 'json' do
    namespace :v1 do
      post 'users/sign_in_via_email'     => 'users#sign_in_via_email'
      get 'listings'     => 'listings#index'
      post 'count_up'     => 'counts#add'
    end
  end
  
  resources :counts, only: [:index, :show]

  #get '*path', controller: 'application', action: 'render_404'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :regulate_user
  before_action :set_guide, only: [:send_request, :destroy, :accept, :reject]
  
  def index
    @friends = current_user.friends_profiles.order_by_created_at_asc.page(params[:page]).per(Settings.friend.page_count)
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def list_search
    @not_friends = current_user.not_friends_profiles.order_by_created_at_asc.page(params[:page]).per(Settings.friend.page_count)
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def send_request
    message = Message.send_firends_message(@guide.id, current_user.id, nil, nil, send_request_params[:message].present? ? send_request_params[:message] : 'no_message')
    if message
      current_user.friend_request(@guide)
      FriendMailer.send_request_notification(current_user, @guide, message.message_thread_id).deliver_now!
      redirect_to message_thread_path(message.message_thread_id), notice: Settings.friend.msg.request
    else
      flash.now[:alert] = Settings.friend.save.failure
      render 'index'
    end
  end
  
  def accept
    message = Message.send_firends_message(@guide.id, current_user.id, Settings.friend.msg.accept, params[:message_thread_id])
    if message
      current_user.accept_request(@guide)
      FriendMailer.send_update_notification(current_user, @guide, message.message_thread_id, Settings.friend.status.accepted).deliver_now!
      redirect_to message_thread_path(message.message_thread_id), notice: Settings.friend.msg.accept
    else
      redirect_to message_thread_path(params[:message_thread_id]), alert: Settings.friend.save.failure
    end
  end
  
  def reject
    message = Message.send_firends_message(@guide.id, current_user.id, Settings.friend.msg.rejected, params[:message_thread_id])
    if message
      current_user.decline_request(@guide)
      #FriendMailer.send_update_notification(current_user, @guide, message.message_thread_id, Settings.friend.status.rejected).deliver_now!
      redirect_to message_thread_path(message.message_thread_id), notice: Settings.friend.msg.rejected
    else
      redirect_to message_thread_path(params[:message_thread_id]), alert: Settings.friend.save.failure
    end
  end
  
  def destroy
    current_user.remove_friend(@guide)
    redirect_to friends_path
  end
  
  def search
    if params[:friends_page]
      if params[:friends_page] == 'true'
        @friends = current_user.search_friends(search_params).page(params[:page]).per(Settings.friend.page_count)
      else
        @not_friends = current_user.search_not_friends(search_params).page(params[:page]).per(Settings.friend.page_count)
      end
    else
      if params[:friends_search]
        @friends = current_user.search_friends(search_params).page(params[:page]).per(Settings.friend.page_count)
      else
        @not_friends = current_user.search_not_friends(search_params).page(params[:page]).per(Settings.friend.page_count)
      end
    end
    respond_to do |format|
      format.js {}
    end
  end
  
  def search_friends
    @friends = current_user.search_friends(search_params).page(params[:page]).per(Settings.friend.page_count)
    respond_to do |format|
      format.js {}
    end
  end
  
  #from booking list
  def friends_list
    session[:guide_ids] = nil if session[:previous_url].blank? or !session[:previous_url].include?('friends')
    @friends = current_user.friends_profiles.order_by_created_at_asc.page(params[:page]).per(Settings.friend.page_count)
    @reservation = Reservation.find(params[:id])
    respond_to do |format|
      if @friends.blank?
        format.html { redirect_to list_search_friends_path }
      else
        format.html
        format.js
      end
    end
  end
  
  def send_message_to_selected_guides
    @reservation = Reservation.find(params[:id])
    if session[:guide_ids].blank?
      redirect_to friends_list_reservation_path(@reservation.id), alert: Settings.friend.send_message_to_selected_guides.failure
    else
      session[:guide_ids].each do |guide_id|
        message = Message.send_message_to_selected_guides(@reservation, guide_id)
        PairGuideMailer.selected_notification(current_user, User.find(guide_id), message.message_thread_id).deliver_now!
      end
      @reservation.pg_under_construction!
      session[:guide_ids] = nil
      redirect_to message_threads_path, notice: Settings.friend.send_message_to_selected_guides.success
    end
  end
  
  #select guide ajax
  def set_selected_guides
    if request.xhr?
      if session[:guide_ids].blank?
        selected_guides = []
        selected_guides.push(params[:guide_id])
        session[:guide_ids] = selected_guides
        return render text: 'added'
      else
        selected_guides = session[:guide_ids]
        if selected_guides.include?(params[:guide_id])
          selected_guides.delete(params[:guide_id])
          session[:guide_ids] = selected_guides
          return render text: 'deleted'
        elsif selected_guides.count > 4
          return render text: 'count_over'
        else
          selected_guides.push(params[:guide_id])
          session[:guide_ids] = selected_guides
          return render text: 'added'
        end
      end
    end
  end
  
  private
  
  def set_guide
    @guide = User.find(params[:id])
  end
  
  def search_params
    params.require(:search).permit(:friends_or_not, :keyword)
  end
  
  def send_request_params
    params.require(:send_request).permit(:message)
  end
  
  def regulate_user
    return redirect_to root_path, alert: Settings.regulate_user.user_id.failure if current_user.guest?
  end
end

app/views/friends/_friends_list.html.slim
#friends_list
  .card-body
    .row-space-8.guide_list-wrapper
      .guide_list-tiles
        .row
          - if friends.present?
            - friends.each do |profile|
              - all_reviewed_count = Review.my_reviewed_count(profile.user_id)
              .col-lg-4.col-md-6.row-space-6
                = render partial: 'shared/guide_card', locals: { all_reviewed_count: all_reviewed_count, profile: profile }

                - if action_name == 'index' or action_name == 'search'
                  = link_to 'メッセージ', message_thread_path(users_to_guide_thread(profile.user_id, current_user.id)), class: "btn btn-primary btn-large btn-block row-space-top-1 row-space-1"
                  = form_tag(friend_path(profile.user_id), method: :delete) do
                    = button_tag(type: "submit", class: "favorite-btn-large btn btn-large btn-block") do
                      i.fa.fa-times
                      | 仲間からはずす
                - elsif action_name == 'friends_list' or action_name == 'search_friends' or controller_name == 'unscheduled_tours'
                  = hidden_field_tag :guide_id, profile.user_id, class: 'guide_id'
                  - if session[:guide_ids].present? and session[:guide_ids].include?(profile.user_id.to_s)
                    = link_to '選択中', '#', class: "btn btn-primary btn-large btn-block row-space-top-1 row-space-1 select_friend_link", id: 'select_friend_link'
                  - else
                    = link_to '候補にする', '#', class: "btn btn-default btn-large btn-block row-space-top-1 row-space-1 select_friend_link", id: 'select_friend_link'
          - else
            .col-md-12.row-space-top-4.row-space-4
              p.text-lead
                | Huber.のTOMODACHI GUIDEは2人1組のペアで行います。ガイド仲間がいないとツアーができません。
              p.text-lead
                | 
                = link_to "「ガイド仲間を探す」", list_search_friends_path
                | から、ガイド仲間を見つけてください。
  .text-center
    = paginate friends, remote: true, params: { friends_page: true}

app/views/friends/_not_friends_list.html.slim
#not_friends_list
  .card-body
    .row-space-8.guide_list-wrapper
      .guide_list-tiles
        .row
          - not_friends.each do |profile|
            - all_reviewed_count = Review.my_reviewed_count(profile.user_id)
            .col-lg-4.col-md-6.row-space-6
              = render partial: 'shared/guide_card', locals: { all_reviewed_count: all_reviewed_count, profile: profile }
              - if current_user.friend_requested?(profile.user_id)
                = link_to '仲間申請が来ています', '#', class: 'btn btn-primary btn-large btn-block row-space-top-1 row-space-1 disabled'
              /- elsif current_user.friend_pending?(profile.user_id)
                = link_to '申請済みです', '#', class: 'btn btn-primary btn-large btn-block row-space-top-1 row-space-1 disabled'
              - else
                = link_to '仲間申請する', '#', class: 'btn btn-primary btn-large btn-block row-space-top-1 row-space-1 message_to_pair_guide_link'
                = render partial: 'shared/modals/message_to_pair_guide', locals: { profile: profile }
  .text-center
    = paginate not_friends, remote: true, params: { friends_page: false}

app/views/friends/friends_list.html.slim
= render partial: 'shared/subnav'
= render partial: 'shared/friends_search_form', locals: { listing: @reservation.listing, friends: @friends}
.text-center.row-space-8
  = form_tag(send_message_to_selected_guides_reservation_path(@reservation.id), method: :post) do
    = submit_tag '選択したガイドに相談する', class: "btn btn-primary btn-large"
  

app/views/friends/friends_list.js.erb
$('#friends_list').html($("<%=j render partial: 'friends/friends_list', locals: { friends: @friends } %>").hide().fadeIn('slow'));
$("html,body").animate({scrollTop:0},'slow');

app/views/friends/index.html.slim
= render partial: 'shared/subnav'
.guide-friend-title.page-container.row-space-top-8.text-center
  h3 ガイド仲間
  = link_to 'ガイド仲間を探す', list_search_friends_path, class: "btn btn-primary btn-radius"
.page-container.row-space-top-4.row-space-8
  .row
    .col-md-12
      .card.row-space-4
        .card-header
          = form_tag(search_friends_path, method: :get, remote: true, id: 'friends_search') do
            .row.row-condensed
              /label.col-md-1.text-right.hide--sp
                | 名前
              .col-xs-8.col-md-6.fieldset
                = text_field 'search', 'keyword', placeholder: "名前で検索"
              .col-xs-4.col-md-2.fieldset
                = submit_tag '検索', class: "btn btn-primary btn-block btn-friend-search", name: 'friends_search'
                /.select.select-block
                  = select 'search', 'friends_or_not', [["仲間", 'friends'], ["その他", 'not_friends']]
        = render partial: 'friends_list', locals: { friends: @friends }
        /= render partial: 'not_friends_list', locals: { not_friends: @not_friends }

app/views/friends/index.js.erb
<% if defined? @friends %>
  $('#friends_list').html($("<%=j render partial: 'friends/friends_list', locals: { friends: @friends } %>").hide().fadeIn('slow'));
  $("html,body").animate({scrollTop:0},'slow');
<% end %>

app/views/friends/list_search.html.slim
= render partial: 'shared/subnav'
.guide-friend-title.page-container.row-space-top-8.text-center
  h3 ガイド仲間を探す
  = link_to 'ガイド仲間一覧に戻る', friends_path, class: "btn btn-primary btn-radius"
.page-container.row-space-top-4.row-space-8
  .row
    .col-md-12
      .card.row-space-4
        .card-header
          = form_tag(search_friends_path, method: :get, remote: true, id: 'friends_search') do
            .row.row-condensed
              /label.col-md-1.text-right.hide--sp
                | 名前
              .col-xs-8.col-md-6.fieldset
                = text_field 'search', 'keyword', placeholder: "名前で検索"
              .col-xs-4.col-md-2.fieldset
                = submit_tag '検索', class: "btn btn-primary btn-block btn-friend-search", friends_page: false
                /.select.select-block
                  = select 'search', 'friends_or_not', [["仲間", 'friends'], ["その他", 'not_friends']]
        /= render partial: 'friends_list', locals: { friends: @friends }
        = render partial: 'not_friends_list', locals: { not_friends: @not_friends }

app/views/friends/list_search.js.erb
<% if defined? @not_friends %>
  $('#not_friends_list').html($("<%=j render partial: 'friends/not_friends_list', locals: { not_friends: @not_friends } %>").hide().fadeIn('slow'));
  $("html,body").animate({scrollTop:0},'slow');
<% end %>

app/views/friends/search.js.erb
<% if defined? @friends %>
  $('#friends_list').html($("<%=j render partial: 'friends/friends_list', locals: { friends: @friends } %>").hide().fadeIn('slow'));
  $("html,body").animate({scrollTop:0},'slow');
<% end %>
<% if defined? @not_friends %>
  $('#not_friends_list').html($("<%=j render partial: 'friends/not_friends_list', locals: { not_friends: @not_friends } %>").hide().fadeIn('slow'));
  $("html,body").animate({scrollTop:0},'slow');
<% end %>

app/views/friends/search_friends.js.erb
$('#friends_list').html($("<%=j render partial: 'friends/friends_list', locals: { friends: @friends } %>").hide().fadeIn('slow'));
$("html,body").animate({scrollTop:0},'slow');