config/routes.rb
Rails.application.routes.draw do
  resources :listing_destinations

  resources :features, only: [:index] do
    collection do
      get 'contents'
      resources :kyoto, :controller => 'features', only: [] do
        get '/' => 'features#kyoto', on: :collection
        get '/' => 'features#contents_kyoto', on: :member
      end
      resources :beppu, :controller => 'features', only: [] do
        get '/' => 'features#beppu', on: :collection
        get '/' => 'features#contents_beppu', on: :member
      end
    end
  end

  resources :ga_campaign_tags, param: :short_url, path: 'cp', only: [:show]

  mount Ckeditor::Engine => '/ckeditor'

  get 'static_pages/cancel_policy_en'
  get 'static_pages/service_agreement_en'
  get 'static_pages/specific_commercial_transactions_en'
  get 'static_pages/privacy_policy_en'
  get 'static_pages/cancel_policy_jp'
  get 'static_pages/service_agreement_jp'
  get 'static_pages/specific_commercial_transactions_jp'
  get 'static_pages/privacy_policy_jp'
  get 'static_pages/about'
  get 'static_pages/plan4U'
  get 'static_pages/plan4U_kyoto', :path => 'static_pages/plan4U-kyoto'
  get 'static_pages/plan4U_hokkaido', :path => 'static_pages/plan4U-hokkaido'
  get 'static_pages/plan4U_kyushu', :path => 'static_pages/plan4U-kyushu'
  get 'static_pages/three_reasons'
  get 'static_pages/our_partners'

  post 'currencies/change_currency'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin::Devise.config
  # begin
  #   ActiveAdmin.routes(self)
  # rescue Exception => e
  #   puts "ActiveAdmin: #{e.class}: #{e}"
  # end

  resources :announcements, param: :page_url, only: [:show, :index]
  resources :reports, only: [:create]
  resources :tag_events, only: [:create]

  resources :profiles do
    resources :profile_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      put 'change_order', on: :collection
      post 'create_cover_image', on: :collection
      post 'check_validation', on: :collection
    end
    resources :profile_videos, only: [:destroy] do
      patch 'upload_video', on: :collection
    end
    resources :profile_banks
    resources :profile_identities, only: [:new, :edit, :create, :update, :destroy]

    member do
      get 'self_introduction',    action: 'self_introduction'
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      delete 'delete_category',    action: 'delete_category'
    end
  end
  
  resources :withdrawals, only: [:index] do
   post 'apply', on: :collection
  end

  get 'dashboard'                           => 'dashboard#index'
  get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
  get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
  get 'dashboard/favorite_histories' => 'dashboard#favorite_histories'
  get 'dashboard/read_more_favorites' => 'dashboard#read_more_favorites'
  post 'dashboard/get_chart_data' => 'dashboard#get_chart_data'
  # get 'reviews'                             => 'profiles#review', as: 'user_review'
  # get 'introductions'                       => 'profiles#introduction', as: 'introduction'
  #get 'pickups/show/:type/:id'                    => 'listing_pickups#show', as: 'pickups_list'

  resources :message_threads, except: [:edit] do
    get 'talk_to_me', on: :member
    post 'what_talk_about', on: :member
    patch 'start_planning', on: :member
    get 'change_language', on: :collection
    post 'create_tomo_dachi_messages', on: :member
  end

  resources :messages do
    collection do
      get 'show_preview'
      get 'download_attached_file'
    end
  end

  resources :pre_mails, only: [:create]

  namespace :search do
    get '/', action: :search
    get 'get_information', action: 'get_information'
    get 'search_result', action: 'search_result'
    #get 'page/:page',    action: 'index'
  end

  resources :listings do
    resources :unscheduled_tours, only: [:new, :create, :show], param: :uuid do
      member do
        get 'complete'
      end
      resource :reviews, only: [:create] do
        get '/', action: :unscheduled_tour
        post '/', action: :create_unscheduled_tour
      end
    end
    
    resources :listing_users, only: [:index, :create, :destroy] do
      # member do
      #   post 'accept'
      #   patch 'add_receptionist'
      # end
    end
    
    resources :listing_images, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
      post 'upload_video_cover_image', on: :collection
      put 'change_order', on: :collection
      delete 'destroy_video', on: :collection
      post 'set_category', on: :member
    end
    resources :listing_details, only: [:show, :create, :update, :destroy] do
      get 'manage', on: :collection
    end

    get 'publish',   action: 'publish',   as: 'publish'
    get 'unpublish', action: 'unpublish', as: 'unpublish'
    get 'preview'
    post 'copy', action: 'copy', as: 'copy'
    post 'change_authorized_user_status'
    member do
      get 'read_more_reviews',    action: 'read_more_reviews'
    end
    collection do
      get 'search'
    end

    resources :ngevents, only: [:create] do
      get 'listing_ngdays', on: :collection
      get 'listing_reservation_ngdays', on: :collection
      get 'listing_request_ngdays', on: :collection
      get 'reservation_except_listing_ngdays', on: :collection
      get 'request_except_listing_ngdays', on: :collection
    end
    resources :ngevent_weeks, only: [:create] do
      get 'listing_ngweeks', on: :collection
      put 'unset', on: :collection
    end
    #resources :calendar
  end

  #resources :spots

  resources :favorites, only: [:create, :destroy] do
    collection do
      get :users
      get :listings
      #get :spots
    end
  end

  resources :pickups, only: [:show]
  resources :friends, only: [:index, :destroy] do
    member do
      post 'send_request'
      post 'accept'
      post 'reject'
    end
    collection do
      get 'list_search'
      get 'search'
      get 'search_friends'
      post 'set_selected_guides'
    end
  end

  resources :reservations, only: [:create, :update] do
    resource :reviews, only: [:create] do
      collection do
        get 'for_guest'
        get 'for_guide'
        post 'create_guest'
        post 'create_guide'
      end
    end
    collection do
      get 'confirm_payment'
      get 'cancel_payment'
      get 'set_reservation_by_listing'
      get 'set_reservation_default'
      get 'set_ngday_reservation_by_listing'
      get 'set_ngday_reservation_default'
      get 'exist_ngday_reservation'
    end
    member do
      get 'friends_list' => 'friends#friends_list'
      post 'send_message_to_selected_guides' => 'friends#send_message_to_selected_guides'
    end
  end

  resources :wishlists
  resources :ngevents do
    get 'reservation_ngdays', on: :collection
    get 'request_ngdays', on: :collection
    get 'common_ngdays', on: :collection
    get 'set_ngday_listing', on: :collection
    get 'select_ngdays', on: :collection
  end
  resources :ngevent_weeks do
    get 'except_common_ngweeks', on: :collection
    get 'common_ngweeks', on: :collection
    get 'set_ngweek_listing', on: :collection
    put 'unset', on: :collection
  end
  resources :calendar do
    get 'common_ngdays', on: :collection
  end

  scope "(:locale)", locale: /ja|en/ do
    resources :help_topics do
      get 'for_user',  on: :collection
      get 'for_guide', on: :collection
      get 'search', on: :collection, action: 'search'
      get 'search_result', on: :collection, action: 'search_result'
    end
  end

  devise_for :users, controllers: {
    sessions:            'users/sessions',
    registrations:       'users/registrations',
    passwords:           'users/passwords',
    omniauth_callbacks:  'users/omniauth_callbacks',
    confirmations:       'users/confirmations'
  }

  devise_scope :user do
    get 'users/withdraw' => 'users/registrations#withdraw'
    get 'users/clear_auth_session' => 'users/registrations#clear_auth_session'
    post 'users/create_email' => 'users/registrations#create_email'
    post 'users/before_omniauth' => 'users/registrations#before_omniauth'
  end

  get "weekly_payment_report" => 'admin/payment#payment_weekly_report'
  get "payment_report_index" => 'admin/payment#index'
  root 'welcome#index'
  
  namespace :api, format: 'json' do
    namespace :v1 do
      post 'users/sign_in_via_email'     => 'users#sign_in_via_email'
      get 'listings'     => 'listings#index'
      post 'count_up'     => 'counts#add'
    end
  end
  
  resources :counts, only: [:index, :show]

  #get '*path', controller: 'application', action: 'render_404'
end

app/models/listing_image.rb
# == Schema Information
#
# Table name: listing_images
#
#  id          :integer          not null, primary key
#  listing_id  :integer
#  image       :string           default("")
#  order_num   :integer
#  caption     :string           default("")
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text             default("")
#  category    :string           default("")
#  pickup_id   :integer
#
# Indexes
#
#  index_listing_images_on_listing_id  (listing_id)
#  index_listing_images_on_pickup_id   (pickup_id)
#

class ListingImage < ActiveRecord::Base
  belongs_to :listing
  belongs_to :pickup

  mount_uploader :image, DefaultImageUploader
  attr_accessor :image_blank_ok
  
  validates :caption, length: { maximum: 100, length:100}

  scope :slideshow_images, -> id { where(listing_id: id) }
  scope :order_asc, -> { order('order_num asc') }
  #scope :cover_image, -> listing_id { where(listing_id: listing_id) }
  scope :records, -> listing_id { where(listing_id: listing_id) }
  scope :image_limit, -> { order('order_num').limit(Settings.listing_images.max_count) }
  
  def self.image_categories
    path = 'image_category/'
    [ { title: 'spa_and_relaxation', image: path + 'spa_icon_01.png'}, { title: 'cultural_sites', image: path + 'culturalsites_icon_01.png'}, {title: 'food_and_drink', image: path + 'food_icon_01.png'}, {title: 'shopping', image: path + 'shopping_icon_01.png'}, { title: 'outdoors', image: path + 'outdoor_icon_01.png'}, { title: 'sports', image: path + 'sports_icon_01.png'},{ title: 'gardens', image: path + 'garden_icon_01.png'},{ title: 'tourist_hotspots', image: path + 'hotspots_icon_01.png'},{ title: 'art', image: path + 'art_icon_01.png'},{ title: 'manga_and_anime', image: path + 'anime_icon_01.png'},{ title: 'onsen', image: path + 'onsen_icon_01.png'},{ title: 'theme_parks',image: path + 'themepark_icon_01.png'},{ title: 'entertainment',image: path + 'entertainment_icon_01.png'},{ title: 'experiences',image: path + 'experience_icon_01.png'}, { title: 'night_life', image: path + 'nightlife_icon_01.png'}]
  end
  
  def category_image
    return '' if self.pickup_id.blank?
    PickupTag.find(self.pickup_id).icon
  end
  
  def category_image_thumb
    return '' if self.pickup_id.blank?
    PickupTag.find(self.pickup_id).icon_small
  end
  
  def self.distance(new_category, old_category)
    new_coutn = 0
    old_count = 0
    PickupTag.all.order_by_created_at_asc.each_with_index do |pickup_tag, i|
      i += 1
      if new_category == pickup_tag.id
        new_coutn = i
      end
      if old_category == pickup_tag.id
        old_count = i
      end
    end
    old_count - new_coutn
  end
  
  def pickup_tag
    PickupTag.find(self.pickup_id)
  end
end

app/controllers/listing_images_controller.rb
class ListingImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing_image, only: [:update, :destroy, :set_category]
  before_action :set_listing
  before_action :regulate_user

  def manage
    @listing_images = @listing.listing_images.order_asc
  end
  
  def upload_video_cover_image
    respond_to do |format|
      if @listing.update(listing_params)
        format.js { @status = 'success' }
      else
        format.js { @status = 'failure' }
      end
    end
  end

  def create
    count = ListingImage.where(listing_id: @listing.id).size
    if count > Settings.listing_images.max_count
      respond_to do |format|
        format.js { @status = 'count_over' }
      end
    end
    
    ActiveRecord::Base.transaction do
      listing_images = []
      create_listing_image_params[:image].each do |image|
        count += 1
        @listing_image = ListingImage.new(listing_id: @listing.id, image: image, order_num: count)
        @listing_image.save!
      end
    end
    respond_to do |format|
      format.js { @status = 'success' }
    end
    
    rescue => e
    p e.message
    respond_to do |format|
      format.js { @status = 'failure' }
    end
  end

  def update
    respond_to do |format|
      if @listing_image.update(listing_image_params)
        format.js { @status = 'success' }
      else
        format.js { @status = 'failure' }
      end
    end
  end

  def destroy
    @listing_image.remove_image!
    @listing_image.destroy
    @listing.listing_images.order('order_num').each_with_index do |listing_image, i|
      listing_image.update(order_num: i + 1)
    end
    @listing.unpublish_if_no_image
    respond_to do |format|
      format.html { redirect_to manage_listing_listing_images_path(@listing.id), notice: Settings.listing_images.delete.success }
      format.json { head :no_content }
    end
  end
  
  def destroy_video
    @listing.remove_cover_video!
    @listing.save
    @listing.unpublish_if_no_image
    respond_to do |format|
      format.html { redirect_to manage_listing_listing_images_path(@listing.id), notice: Settings.listing_images.delete.success }
      format.json { head :no_content }
    end
  end
  
  def change_order
    if request.xhr?
      listing = Listing.find(params[:listing_id])
      image_from = ListingImage.where(listing_id: listing.id, order_num: params[:image_from]).first
      image_to = ListingImage.where(listing_id: listing.id, order_num: params[:image_to]).first
      image_from.update(order_num: params[:image_to])
      image_to.update(order_num: params[:image_from])
        
      @listing_images = listing.listing_images
      render partial: 'images_list', locals: { cover_video: listing.cover_video, listing_images: @listing_images.order_asc}
    end
  end
  
  def set_category
    if request.xhr?
      distance = ListingImage.distance(params[:pickup_id].to_i, @listing_image.pickup_id)
      params[:pickup_id] = '' if distance == 0
      if @listing_image.update(pickup_id: params[:pickup_id])
        return render text: distance
        #return render partial: 'shared/modals/set_listing_image', locals: { listing: @listing, listing_image: @listing_image}
      else
        raise
      end
    end
  end

  private
    def set_listing_image
      @listing_image = ListingImage.find(params[:id])
    end

    def set_listing
      @listing = Listing.find(params[:listing_id])
    end

    def listing_image_params
      params.require(:listing_image).permit(:listing_id, :image, :caption)
    end
  
    def create_listing_image_params
      params.require(:listing_image).permit(:listing_id, image: [])
    end
  
    def listing_params
      params.require(:listing).permit(:cover_video, :not_valid_ok)
    end
  
    def regulate_user
      return redirect_to root_path, alert: Settings.regulate_user.user_id.failure if @listing.user_id != current_user.id or !current_user.has_listing_admin_authority?
    end

end

app/views/listing_images/_cover_video.html.slim
#cover_video
  - if listing.cover_video.present?
    .row.row-space-5.row-space-top-5.row-table
      .col-xs-4.text-right.col-middle
        .h4.text-light
          | 現在のツアー紹介動画
      .col-xs-8.fieldset.col-middle
        .row
          .col-xs-11.regist-pics
            .listing-video-container
              = video_player src: { mp4: listing.cover_video.encoded, webm: listing.cover_video.encoded }, controls: true, width: "100%", height: "315", id: "tour_movie"
              = link_to destroy_video_listing_listing_images_path(listing.id), method: 'DELETE', class: "delete-image balloon", title: "削除する", data: {confirm: '本当に削除しますか？'} do
                i.fa.fa-trash

app/views/listing_images/_form.html.slim
.row
  .col-lg-10.col-lg-offset-1
    #hidden-form-id
    = hidden_field_tag  :listing_id, @listing.id
    .row.row-condensed.row-space-5.add-listing-images
      .col-xs-6.add-listing-images-movie
        = simple_form_for(@listing, url: upload_video_cover_image_listing_listing_images_url(@listing), html: { id: 'upload_video'}, method: 'POST', remote: true) do |f|
          = f.file_field :cover_video, as: :file, class: "", accept: "video/*"
          = f.hidden_field :not_valid_ok, value: true
      .col-xs-6.add-listing-images-image
        = simple_form_for([@listing, ListingImage.new(listing_id: @listing.id)], html: { id: 'upload_image'}, remote: true) do |f|
          = f.hidden_field :listing_id, value: @listing.id
          = f.file_field :image, as: :file, id: 'listing_image_new', multiple: true, accept: "image/jpg, image/jpeg, image/gif, image/png"

  .col-md-12
    = render partial: 'images_list', locals: { cover_video: @listing.cover_video, listing_images: @listing_images}
    hr
    .row.row-space-top-6
      .col-xs-9.col-offset-3.text-reset-center
        = link_to "次のステップへ", manage_listing_listing_details_path(@listing), class: "btn btn-primary btn-large"

app/views/listing_images/_images_list.html.slim
#images_list
  .row
    - if cover_video.present?
      .col-lg-6.row-space-4.regist-pics
        .listing-video-container
          = video_player src: { mp4: @listing.cover_video.encoded, webm: @listing.cover_video.encoded }, controls: true, width: "100%", height: "240px", id: "tour_movie"
          = link_to destroy_video_listing_listing_images_path(@listing.id), method: 'DELETE', class: "delete-image balloon", title: "削除する", data: {confirm: '本当に削除しますか？'} do
            i.fa.fa-trash
    - listing_images.each_with_index do |listing_image, i|
      - pickup_tag = listing_image_to_pickup_tag(listing_image)
      .col-lg-6.row-space-4.regist-pics
        .image-droppable.image-draggable
          .card
            .listing-image-container
              div[style="background-image: url(#{asset_path listing_image.image.thumb})"]
              = link_to listing_listing_image_path(listing_image.listing_id, listing_image), method: 'DELETE', class: "delete-image balloon", title: "削除する", data: {confirm: '本当に削除しますか？'} do
                i.fa.fa-trash
            /.category-container.text-right
              - if pickup_tag.blank?
                = link_to '#', class: 'set_listing_image_link small1', listing_image_id: listing_image.id do
                  i.fa.fa-question.media-round
                  | カテゴリーを設定する
              - else
                = link_to '#', class: 'set_listing_image_link', listing_image_id: listing_image.id do
                  .media-avatar
                    = image_tag pickup_tag.icon_small, class: 'media-round size44'
                  = pickup_tag.short_name
                  /= debug listing_image
            .card-body
              = link_to '#', class: 'set_listing_image_link set_listing_image_link_text small1 row-space-1', listing_image_id: listing_image.id do
                - if listing_image.caption.present?
                  = listing_image.caption
                - else
                  i.fa.fa-plus-circle
                  | 写真に説明を付ける
      = render partial: 'shared/modals/set_listing_image', locals: { listing: @listing, listing_image: listing_image}
    .col-lg-6.row-space-4.regist-pics
      = link_to '#', class: "add-image-link" do
        i.fa.fa-image.row-space-2.row-space-top-8
        span.h5.add-text
          i.fa.fa-plus
          |  Add image

app/views/listing_images/_listing_help_block.html.slim
.listing_help_block.text-muted
  h3.listing-help-sp-header.text-center
    | 登録のヒント
  #tour-video-help.panel.manage-listing-help-panel
    .listing-help-icon-container.text-center
      span.listing-help-icon
    .panel-body
      h4.text-center 動画
      p
        |iPhoneユーザーは
        = link_to "https://itunes.apple.com/us/app/clipbox-1seccamera/id980538523?mt=8", target: "_blank" do
          | 「1secCamera」
      p
        | 、Androidユーザーは
        = link_to "https://play.google.com/store/apps/details?id=net.rena.roadmovie.lite", target: "_blank" do
          | 「SnapMovie (road movie maker)」
        | のご利用を推奨しています。
      p
        | 容量は25MBまでです。
      p
        | 動画の登録は1本のみです。
        
  #tour-image-help.panel.manage-listing-help-panel
    .listing-help-icon-container.text-center
      span.listing-help-icon
    .panel-body
      h4.text-center 写真と動画
      p
        | 写真と動画は、ツアー公開後も追加編集できます。
      p
        | どんどん新しい写真を追加して、あなた自身が参加したいと思うようなツアーにしましょう。

app/views/listing_images/create.js.erb
<% if @status == "count_over" %>
  alert("写真の登録は最大50枚までです。")
<% elsif @status == "success" %>
  var image = '';
  $('#listing-image-success').on('show.bs.modal', function(e) {
    if (image != ''){
      $('#upload-image').css('background-image', 'url('+image+')');
    } else {
      $('#upload-image').css('display', 'none');
      $('#listing-image-success .card-body').css('padding-bottom', '0');
    }
  }).modal('show');
  window.setTimeout(function () {
    $('#listing-image-success').modal('hide');
    location.reload();
  }, 3000);
<% elsif @status == "failure" %>
  $('.alert').remove();
$('#error_message').html($("<%=j render partial: 'error_message', locals: { target: @listing_image } %>").hide().fadeIn('slow'));
  $("html,body").animate({scrollTop:0},'slow');
<% end %>

app/views/listing_images/manage.html.slim
/ listings_images#new
= render partial: 'error_message', locals: { target: @listing}
= render partial: 'error_message', locals: { target: @listing_image} if @listing_image.present?
.manage-listings
  /= render partial: 'shared/manage_listing_header', locals: { listing: @listing }
  = render partial: 'shared/subnav', locals: { listing: @listing }
  = render partial: "shared/manage_listing_nav_sp"
  .manage-listing-row-container
    .manage-listing-content.col-md-5.col-lg-6.col-offset-3
      .row-space-top-4
        h3.text-center.row-space-2 ツアーの写真と動画を追加しましょう。
        p.text-center.row-space-4
          | ゲストに魅力をよく伝えるために、写真や動画を登録しましょう。
      = render 'form'
    .manage-listing-edit.col-md-4.col-lg-3
      = render 'listing_help_block'
    = render partial: 'shared/manage_listing_nav'
= render partial: 'shared/modals/listing_image_loading'
= render partial: 'shared/modals/listing_image_success'
= render partial: 'shared/modals/form_change_confirm'
.listing-help-sp-wrapper
  = link_to "#", class: "edit-help--sp" do
    span.listing-help-icon

app/views/listing_images/update.js.erb
<% if @status == "success" %>
  $('.alert').remove();
  $('#listing-image-loading').modal('hide');
  $('#images_list').html($("<%=j render partial: 'images_list', locals: { cover_video: @listing.cover_video, listing_images: @listing.listing_images.order_asc} %>").hide().fadeIn('slow'));
  $('.image-draggable').draggable({revert: 'invalid', scroll: true, zIndex: 1});
  $('.image-droppable').droppable({activeClass: 'image-drag-active', hoverClass: 'image-drag-hover', tolerance: 'intersect'});
  $('#set_listing_image').hide
<% elsif @status == "failure" %>
  $('.alert').remove();
  $('#listing-image-loading').modal('hide');
  $('#images_list').html($("<%=j render partial: 'images_list', locals: { cover_video: @listing.cover_video, listing_images: @listing.listing_images.order_asc} %>").hide().fadeIn('slow'));
  $('#error_message').html($("<%=j render partial: 'error_message', locals: { target: @listing_image } %>").hide().fadeIn('slow'));
  $('#set_listing_image').hide
  $("html,body").animate({scrollTop:0},'slow');
<% end %>

app/views/listing_images/upload_video_cover_image.js.erb
<% if @status == "success" %>
  var image = '';
  var formId = $('#hidden-form-id').val()
  $('#listing-image-success').on('show.bs.modal', function(e) {
    if (image != ''){
      $('#upload-image').css('background-image', 'url('+image+')');
    } else {
      $('#upload-image').css('display', 'none');
      $('#listing-image-success .card-body').css('padding-bottom', '0');
    }
  }).modal('show');
  window.setTimeout(function () {
    $('#listing-image-success').modal('hide');
    location.reload();
  }, 3000);
<% elsif @status == "failure" %>
  $('.alert').remove();
  $('#error_message').html($("<%=j render partial: 'error_message', locals: { target: @listing } %>").hide().fadeIn('slow'));
  $("html,body").animate({scrollTop:0},'slow');
<% end %>